#include "db_local.h"
#include <QDebug>
#include <QStandardPaths>
#include <QDir>

// groups and vault content tables could be consolidated, only content model is needed

// in production, the default connection name is databaseName param
DB_LocalStorage::DB_LocalStorage(QObject *parent, const QString &databaseName)
    : QObject(parent),
      m_connected(false),
      m_databaseName(databaseName)
{
}

DB_LocalStorage::~DB_LocalStorage() {
    if (_db.open()) {
        _db.close();
    }
}

bool DB_LocalStorage::isDBConnected() {
    return m_connected;
}

bool DB_LocalStorage::initDB() {
    // write path that Sql writes file to
    // path is hardcoded into method for consistent, valid paths across platforms
    // AppDataLocation is the standard path for persistent data

    // database name ":memory:" for testing purposes
    QString dbPath;
    if (m_databaseName == ":memory:") {
        dbPath = ":memory:";
    }
    else {
        QString appDataPath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);
        QDir dir(appDataPath);
        if (!dir.exists() && !dir.mkpath(appDataPath)) {
            qCritical() << "Directory creation failed at " << appDataPath;
            return false;
        }
        dbPath = dir.filePath(m_databaseName + ".sqlite");

        emit directoryEstablished(appDataPath);
        emit databasePathEstablished(dbPath);
    }

    if (QSqlDatabase::contains(m_databaseName)) {
        // if database exists, connect to database
        _db = QSqlDatabase::database(m_databaseName);
    }
    else {
        // if database was not found: add, connect, open, and set database name
        _db = QSqlDatabase::addDatabase("QSQLITE", m_databaseName);
    }

    _db.setDatabaseName(dbPath);

    if (!_db.open()) {
        emit startDBConnectionFailure(_db.lastError());
        return false;
    }

    // create tables and enable foreign_keys
    QSqlQuery _query(_db);
    // _query.exec("PRAGMA foreign_keys = ON;");
    // groups table
    // slug to be added, removed now for base testing
    _query.exec("CREATE TABLE IF NOT EXISTS groups ( "
                   "id INTEGER PRIMARY KEY AUTOINCREMENT, "
                   "name TEXT NOT NULL UNIQUE, "
                   "created_at DATETIME DEFAULT CURRENT_TIMESTAMP)");
    // vault_content table
    _query.exec("CREATE TABLE IF NOT EXISTS vault_content ( "
                   "group_id INTEGER PRIMARY KEY AUTOINCREMENT, "
                   "content_id INTEGER PRIMARY KEY AUTOINCREMENT, "
                   "org_name TEXT, "
                   "username TEXT, "
                   "password TEXT NOT NULL, "
                   "FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE)");


    m_connected = true;
    emit startDBConnectionSuccess();
    return true;
}

void DB_LocalStorage::closeDB() {
    _db.close();

    if (_db.isOpen()) {
        emit closeDBConnectionFailure(_db.lastError());
        return;
    }

    emit closeDBConnectionSuccess();
}

// addGroup() return type int so that the unique ID generated by SQL can reference a group
int DB_LocalStorage::addGroup(const QString &groupName) {
    if (!m_connected || !_db.isOpen()) {
        qDebug() << "Database error: could not create tables [groups]";
        return -1;
    }
    QSqlQuery _query(_db);
    _query.prepare("INSERT INTO groups (name) VALUES (:name)");
    _query.bindValue(":name", groupName);
    // slug will reference url path in-app (i.e. home/my_vault/)
    // _query.bindValue(":slug", slugToBeAdded)
    if (!_query.exec()) {
        emit databaseQueryError(_query.lastError());
        return -1;
    }

    emit databaseQuerySuccess();
    return _query.lastInsertId().toInt();
}

// returns the group name that matches the given group id
// primarily for debugging
QString DB_LocalStorage::fetchGroupName(int groupID) {
    QSqlQuery _query(_db);
    _query.prepare("SELECT name FROM groups WHERE id = :groupID");
    _query.bindValue(":groupID", groupID);
    if (_query.exec() && _query.next()) {
        return _query.value(0).toString();
    }

    return QString();
}

bool DB_LocalStorage::renameGroup(int groupID, const QString &newGroupName) {
    QSqlQuery _query(_db);
    _query.prepare("UPDATE groups SET name = :newName WHERE id = :groupID");
    _query.bindValue(":newName", newGroupName);
    _query.bindValue(":groupID", groupID);
    if (!_query.exec()) {
        emit databaseQueryError(_query.lastError());
        return false;
    }

    emit databaseQuerySuccess();
    return true;
}

// _query that removes an entire group: called when a user deletes a group through qml interaction
// foreign keyed group_id in vault_content should have associated rows removed
bool DB_LocalStorage::removeGroup(int groupID) {
    QSqlQuery _query(_db);
    _query.prepare("DELETE FROM groups WHERE id = :groupID");
    _query.bindValue(":groupID", groupID);
    if(!_query.exec()) {
        emit databaseQueryError(_query.lastError());
        return false;
    }

    emit databaseQuerySuccess();
    return true;
}

// requires additional columns for content types: organization, username, password
// requires long form of string (QString or QTextStream input?) parameter
bool DB_LocalStorage::addVaultRowEntry(int currGroupID, const QString &organizationName, const QString &username, const QString &pass) {
    QSqlQuery _query(_db);
    _query.prepare("INSERT INTO vault_content (group_id, org_name, username, password) VALUES (:gid, :org, :usr, :pw)");
    _query.bindValue(":gid", currGroupID);
    _query.bindValue(":org", organizationName);
    _query.bindValue(":usr", username);
    _query.bindValue(":pw", pass);
    if (!_query.exec()) {
        emit databaseQueryError(_query.lastError());
        return false;
    }

    emit databaseQuerySuccess();
    return true;
}

// retrieves all credentials from a group
QList DB_LocalStorage::fetchCredentials(int currGroupID) {
    QSqlQuery _query(_db);
    _query.prepare("SELECT org_name, username, password FROM vault_content WHERE group_id = :currGroupID");
    _query.bindValue(":currGroupID", currGroupID);

    if (!query.exec()) {
        emit databaseQueryError(_query.lastError);
        return false;
    }

    emit databaseQuerysuccess();
    return true;

}

